#image:
#  name: ${ARTIFACTORY_URL}:5000/centos:7.6.1810


stages:
  - build
  - test

before_script:
  - echo "ENV=$ENV"

BUILD:
  stage: build
  script:
  - curl -O  -k https://${ARTIFACTORY_URL}/artifactory/artifactory_yum_repo_config/artifactory-pub-centos7.repo
  - mkdir repofiles
  - mv artifactory-pub-centos7.repo repofiles/repofile-`date +"%m-%d-%y-%s"`
  artifacts:
      paths:
      - repofiles/
  tags:
  - re-mac-runner

TEST:
  stage: test
  script:
  - echo "Running tests in $ENV environment"
  - ls -alR
  dependencies:
      - BUILD
  tags:
  - re-mac-runner

after_script:
   - echo "Done"
#  - docker rm -v $(docker ps --filter status=exited -q | grep -v -E $(docker ps -aq --filter='name=runner' | paste -sd "|" -) 2>/dev/null) &>/dev/null || true
#  - docker rmi $(docker images | grep "none" | awk '/ / { print $3 }') &>/dev/null || true
#  - docker rmi $(docker images --filter dangling=true -q 2>/dev/null) &>/dev/null || true
