image:
  name: ${ARTIFACTORY_URL}:5000/centos:7.6.1810

stages:
  - build
  - test

before_script:
  - echo "ENV=$ENV"

BUILD:
  stage: build
  script:
  - echo "Running build in $ENV environment"
  - cat /etc/centos-release
  - whoami
  - curl -O  -k https://${ARTIFACTORY_URL}/artifactory/artifactory_yum_repo_config/artifactory-pub-centos7.repo
  - ls -l 
  - ls -al /cache
  - [[ -d /cache/gitlab-runner-testing ]] && rm -rf /cache/gitlab-runner-testing
  - mkdir /cache/gitlab-runner-testing
  - echo "testing" >> /cache/gitlab-runner-testing/testfile.txt
  - cat /etc/centos-release
  - pwd
  - chmod +x builds/*
  - cd builds
  - ./spawn_build.sh
  tags:
  - cel-test-cache

TEST:
  stage: test
  script:
  - echo "Running tests in $ENV environment"
  - cat /etc/centos-release
  - cat /cache/gitlab-runner-testing/testfile.txt
  - rm -rf /cache/gitlab-runner-testing
  - curl -O  -k https://${ARTIFACTORY_URL}/artifactory/artifactory_yum_repo_config/artifactory-pub-centos7.repo
  - ls -l 
  - pwd
  - chmod +x tests/test.sh
  - tests/test.sh
  tags:
  - cel-test-cache

after_script:
  - docker rm -v $(docker ps --filter status=exited -q | grep -v -E $(docker ps -aq --filter='name=runner' | paste -sd "|" -) 2>/dev/null) &>/dev/null || true
  - docker rmi $(docker images | grep "none" | awk '/ / { print $3 }') &>/dev/null || true
  - docker rmi $(docker images --filter dangling=true -q 2>/dev/null) &>/dev/null || true
